name: Deploy Docker Image to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}   # Use AWS_REGION as an environment variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   # AWS Access Key from GitHub Secrets
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # AWS Secret Key from GitHub Secrets

    # # Step 3: Build and push Docker image into docker
    # - name: Build and push Docker image
    #   run: |
    #     docker build -t mnist-gradio-app .
    #     docker tag mnist-gradio-app:latest 841162707028.dkr.ecr.us-east-1.amazonaws.com/mnist/gradio-app:latest
    #     docker push 841162707028.dkr.ecr.us-east-1.amazonaws.com/mnist/gradio-app:latest
    
    # Step 4: Deploy to EC2
    - name: Connect to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        debug: true  # Enable verbose output
        script: echo "Connected to EC2 instance"

    - name: Pull Docker Image from ECR
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
            sudo docker pull 841162707028.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mnist/gradio-app:latest

    - name: Stop Existing Docker Container
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
            sudo docker stop gradio-app || true

    - name: Remove Existing Docker Container
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
            sudo docker rm gradio-app || true

    - name: Run New Docker Container
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
            sudo docker run -d -p 7860:7860 --name gradio-app 841162707028.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mnist/gradio-app:latest
