name: Deploy Docker Image to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Uncomment and modify the build step as needed
    # - name: Build and push Docker image
    #   run: |
    #     docker build -t mnist-gradio-app .
    #     docker tag mnist-gradio-app:latest 841162707028.dkr.ecr.us-east-1.amazonaws.com/mnist/gradio-app:latest
    #     docker push 841162707028.dkr.ecr.us-east-1.amazonaws.com/mnist/gradio-app:latest

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ubuntu
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'EOF'
          # Configure AWS CLI if needed
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 841162707028.dkr.ecr.$AWS_REGION.amazonaws.com
          
          # Pull new image
          docker pull 841162707028.dkr.ecr.$AWS_REGION.amazonaws.com/mnist/gradio-app:latest
          
          # Stop and remove existing container
          docker stop gradio-app || true
          docker rm gradio-app || true
          
          # Run new container
          docker run -d -p 7860:7860 --name gradio-app \
            841162707028.dkr.ecr.$AWS_REGION.amazonaws.com/mnist/gradio-app:latest
        EOF