name: Deploy Docker Image to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Install Dependencies and Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ubuntu
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REGISTRY: 841162707028.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      run: |
        ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << 'ENDSSH'
          # Install AWS CLI if not present
          if ! command -v aws &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y awscli
          fi

          # Set AWS region
          aws configure set region ${AWS_REGION}

          # Get ECR login token and login to Docker
          aws ecr get-login-password --region ${AWS_REGION} | sudo docker login --username AWS --password-stdin ${ECR_REGISTRY}

          # Pull new image
          sudo docker pull ${ECR_REGISTRY}/mnist/gradio-app:latest

          # Stop and remove existing container (if exists)
          sudo docker ps -q --filter "name=gradio-app" | grep -q . && sudo docker stop gradio-app
          sudo docker ps -aq --filter "name=gradio-app" | grep -q . && sudo docker rm gradio-app

          # Run new container
          sudo docker run -d \
            --name gradio-app \
            -p 7860:7860 \
            ${ECR_REGISTRY}/mnist/gradio-app:latest
        ENDSSH